import type { Lang } from "./languages";

type LocalizedPhrase = readonly [english: string, german: string, spanish: string, czech: string];

/**
 * Some screens predate the keyed translation catalogue. This exact-copy
 * table lets the translation bridge localize them while they are gradually
 * migrated to t("…") calls. It intentionally contains interface copy only:
 * names, deck content, answers and blog article content are never translated.
 */
const PHRASES: LocalizedPhrase[] = [
  ["Account", "Konto", "Cuenta", "Účet"],
  ["Welcome to KatchUp", "Willkommen bei KatchUp", "Bienvenido a KatchUp", "Vítejte v KatchUp"],
  ["Ready to test your vocabulary? Sign in to save your progress, or jump right into the action and play as a guest first.", "Bereit, deinen Wortschatz zu testen? Melde dich an, um deinen Fortschritt zu speichern, oder spiele zuerst als Gast.", "¿Listo para poner a prueba tu vocabulario? Inicia sesión para guardar tu progreso o juega primero como invitado.", "Chcete si otestovat slovní zásobu? Přihlaste se pro uložení pokroku, nebo si nejdřív zahrajte jako host."],
  ["Currently signed in as", "Angemeldet als", "Sesión iniciada como", "Přihlášen jako"],
  ["Continue to Home", "Weiter zur Startseite", "Continuar al inicio", "Pokračovat na hlavní stránku"],
  ["Last used", "Zuletzt verwendet", "Usado por última vez", "Naposledy použito"],
  ["Continue with Google", "Mit Google fortfahren", "Continuar con Google", "Pokračovat přes Google"],
  ["Continue with GitHub", "Mit GitHub fortfahren", "Continuar con GitHub", "Pokračovat přes GitHub"],
  ["Continue with Discord", "Mit Discord fortfahren", "Continuar con Discord", "Pokračovat přes Discord"],
  ["Or", "Oder", "O", "Nebo"],
  ["Play Games as Guest", "Als Gast spielen", "Jugar como invitado", "Hrát jako host"],
  ["Sign in", "Anmelden", "Iniciar sesión", "Přihlásit se"],
  ["Sign out", "Abmelden", "Cerrar sesión", "Odhlásit se"],
  ["Signed in as", "Angemeldet als", "Sesión iniciada como", "Přihlášen jako"],
  ["Go home", "Zur Startseite", "Ir al inicio", "Přejít domů"],
  ["Primary", "Hauptnavigation", "Navegación principal", "Hlavní navigace"],

  ["Online Games", "Online-Spiele", "Juegos en línea", "Online hry"],
  ["Learn words", "Lerne Wörter", "Aprende palabras", "Učte se slova"],
  ["by playing.", "beim Spielen.", "jugando.", "hraním."],
  ["Practice vocabulary with fast rounds, live competition, and adaptive challenge levels. Everything here is built to feel like play, not homework.", "Übe Wortschatz in schnellen Runden, Live-Duellen und mit passender Schwierigkeit. Hier fühlt sich alles nach Spielen an, nicht nach Hausaufgaben.", "Practica vocabulario con rondas rápidas, competición en directo y dificultad adaptativa. Todo está pensado para sentirse como un juego, no como deberes.", "Procvičujte slovní zásobu v rychlých kolech, živých soubojích a s přizpůsobenou obtížností. Všechno působí jako hra, ne jako domácí úkol."],
  ["Ready to play? 👋", "Bereit zum Spielen? 👋", "¿Listo para jugar? 👋", "Připraveni hrát? 👋"],
  ["Top picks - online", "Top-Auswahl – online", "Destacados en línea", "Nejlepší online hry"],
  ["Explore more", "Mehr entdecken", "Explorar más", "Prozkoumat další"],
  ["Browse games", "Spiele entdecken", "Explorar juegos", "Procházet hry"],
  ["Play now", "Jetzt spielen", "Jugar ahora", "Hrát nyní"],
  ["LET'S PLAY", "LOS GEHT'S", "VAMOS A JUGAR", "POJĎME HRÁT"],
  ["Next slide", "Nächste Folie", "Siguiente", "Další snímek"],
  ["Scroll left", "Nach links", "Desplazar a la izquierda", "Posunout doleva"],
  ["Scroll right", "Nach rechts", "Desplazar a la derecha", "Posunout doprava"],
  ["Live Duel", "Live-Duell", "Duelo en directo", "Živý souboj"],
  ["Bot Duel", "Bot-Duell", "Duelo contra el bot", "Souboj s botem"],
  ["Score Rush", "Punktejagd", "Carrera de puntos", "Honba za body"],
  ["Flip Cards", "Lernkarten", "Tarjetas", "Obrácené karty"],
  ["One of Three", "Eins von drei", "Una de tres", "Jeden ze tří"],
  ["Speed Spelling", "Schnelles Buchstabieren", "Escritura rápida", "Rychlé psaní"],
  ["Word Pairing", "Wortpaare", "Emparejar palabras", "Párování slov"],
  ["Quick choice rounds", "Schnelle Auswahlrunden", "Rondas rápidas de elección", "Rychlá kola s výběrem"],
  ["Self-paced flashcards", "Lernkarten ohne Zeitdruck", "Tarjetas a tu ritmo", "Kartičky vlastním tempem"],
  ["Type it before time runs out", "Tippe, bevor die Zeit abläuft", "Escribe antes de que acabe el tiempo", "Napište slovo, než vyprší čas"],
  ["Connect the synonyms", "Verbinde passende Wörter", "Une las palabras correspondientes", "Spojte odpovídající slova"],
  ["30 seconds, as many words as you can", "30 Sekunden, so viele Wörter wie möglich", "30 segundos, tantas palabras como puedas", "30 sekund, co nejvíce slov"],
  ["Duel an online opponent or the bot", "Duelliere dich online oder gegen den Bot", "Enfréntate a otra persona o al bot", "Vyzvěte online soupeře nebo bota"],

  ["Get Ready", "Mach dich bereit", "Prepárate", "Připravte se"],
  ["Language:", "Sprache:", "Idioma:", "Jazyk:"],
  ["Difficulty matched to your level", "Schwierigkeit passend zu deinem Level", "Dificultad adaptada a tu nivel", "Obtížnost odpovídá vaší úrovni"],
  ["Score:", "Punkte:", "Puntuación:", "Skóre:"],
  ["Accuracy:", "Genauigkeit:", "Precisión:", "Přesnost:"],
  ["pts", "Pkt.", "pts", "bodů"],
  ["Pick the correct translation", "Wähle die richtige Übersetzung", "Elige la traducción correcta", "Vyberte správný překlad"],
  ["Wrong answer", "Falsche Antwort", "Respuesta incorrecta", "Špatná odpověď"],
  ["Correct!", "Richtig!", "¡Correcto!", "Správně!"],
  ["Correct answers:", "Richtige Antworten:", "Respuestas correctas:", "Správné odpovědi:"],
  ["Play Again", "Nochmal spielen", "Jugar otra vez", "Hrát znovu"],
  ["Play again", "Nochmal spielen", "Jugar otra vez", "Hrát znovu"],
  ["Back to lobby", "Zurück zur Lobby", "Volver a la sala", "Zpět do lobby"],
  ["Back to games", "Zurück zu den Spielen", "Volver a los juegos", "Zpět na hry"],
  ["Back to decks", "Zurück zu den Decks", "Volver a los mazos", "Zpět na balíčky"],
  ["Back to topic", "Zurück zum Thema", "Volver al tema", "Zpět na téma"],
  ["Continue playing", "Weiterspielen", "Seguir jugando", "Pokračovat ve hře"],
  ["Continue practicing", "Weiterüben", "Seguir practicando", "Pokračovat v procvičování"],
  ["Replay lesson", "Lektion wiederholen", "Repetir la lección", "Zopakovat lekci"],
  ["Next round", "Nächste Runde", "Siguiente ronda", "Další kolo"],
  ["Finish Round", "Runde beenden", "Terminar ronda", "Dokončit kolo"],
  ["Finish round", "Runde beenden", "Terminar ronda", "Dokončit kolo"],
  ["Lesson completed", "Lektion abgeschlossen", "Lección completada", "Lekce dokončena"],
  ["Try once more", "Noch einmal versuchen", "Intentarlo otra vez", "Zkusit ještě jednou"],
  ["Passed", "Bestanden", "Superado", "Splněno"],
  ["Failed", "Nicht bestanden", "No superado", "Nesplněno"],
  ["Progress", "Fortschritt", "Progreso", "Pokrok"],
  ["Known", "Gewusst", "Conocidas", "Znám"],
  ["Still learning", "Noch am Lernen", "Aún aprendiendo", "Stále se učím"],
  ["Know it", "Weiß ich", "La sé", "Znám to"],
  ["Tap to flip", "Zum Umdrehen tippen", "Toca para girar", "Klepnutím otočte"],
  ["Tap to flip back", "Zum Zurückdrehen tippen", "Toca para volver", "Klepnutím otočte zpět"],
  ["Your language", "Deine Sprache", "Tu idioma", "Váš jazyk"],
  ["Translation", "Übersetzung", "Traducción", "Překlad"],
  ["Type the Translation", "Übersetzung eingeben", "Escribe la traducción", "Napište překlad"],
  ["Type this word", "Tippe dieses Wort", "Escribe esta palabra", "Napište toto slovo"],
  ["Start typing...", "Jetzt tippen…", "Empieza a escribir…", "Začněte psát…"],
  ["Check", "Prüfen", "Comprobar", "Zkontrolovat"],
  ["I already know this", "Das weiß ich schon", "Ya la conozco", "Tohle už znám"],
  ["Counted as practice", "Als Übung gezählt", "Contado como práctica", "Započítáno jako procvičování"],
  ["No words available for this round yet.", "Für diese Runde sind noch keine Wörter verfügbar.", "Todavía no hay palabras para esta ronda.", "Pro toto kolo zatím nejsou dostupná žádná slova."],
  ["Deck not found", "Deck nicht gefunden", "No se encontró el mazo", "Balíček nebyl nalezen"],
  ["Sign in to practice this deck", "Melde dich an, um dieses Deck zu üben", "Inicia sesión para practicar este mazo", "Přihlaste se a procvičujte tento balíček"],
  ["No words to practice right now", "Gerade gibt es keine Wörter zum Üben", "No hay palabras para practicar ahora", "Teď nejsou žádná slova k procvičování"],

  ["Duel Setup", "Duell einrichten", "Configuración del duelo", "Nastavení souboje"],
  ["Compete live against another player, or race a bot. Either way, the first to 10 correct answers wins.", "Tritt live gegen andere oder einen Bot an. Wer zuerst 10 richtige Antworten hat, gewinnt.", "Compite en directo contra otra persona o contra el bot. Gana quien llegue primero a 10 respuestas correctas.", "Soutěžte živě proti hráči nebo botovi. Vyhrává první s 10 správnými odpověďmi."],
  ["Matchmaking Mode (live duels)", "Spielersuche (Live-Duelle)", "Emparejamiento (duelos en directo)", "Hledání soupeře (živé souboje)"],
  ["Personalized Mode", "Personalisierter Modus", "Modo personalizado", "Přizpůsobený režim"],
  ["Fair Mode", "Fairer Modus", "Modo justo", "Férový režim"],
  ["Same words for both players", "Gleiche Wörter für beide", "Las mismas palabras para ambos", "Stejná slova pro oba hráče"],
  ["Start Live Duel", "Live-Duell starten", "Iniciar duelo en directo", "Spustit živý souboj"],
  ["Searching opponent", "Gegner wird gesucht", "Buscando rival", "Hledám soupeře"],
  ["Cancel Matchmaking", "Spielersuche abbrechen", "Cancelar búsqueda", "Zrušit hledání"],
  ["Duel the bot instead", "Stattdessen gegen den Bot", "Jugar contra el bot", "Místo toho hrát s botem"],
  ["Opponent found:", "Gegner gefunden:", "Rival encontrado:", "Soupeř nalezen:"],
  ["Accept duel", "Duell annehmen", "Aceptar duelo", "Přijmout souboj"],
  ["Waiting for", "Warten auf", "Esperando a", "Čekám na"],
  ["to accept...", "Annahme…", "que acepte…", "přijetí…"],
  ["Recent duels:", "Letzte Duelle:", "Duelos recientes:", "Nedávné souboje:"],
  ["Match finished", "Spiel beendet", "Partida terminada", "Souboj skončil"],
  ["This duel has ended", "Dieses Duell ist beendet", "Este duelo ha terminado", "Tento souboj skončil"],

  ["30 Second Challenge", "30-Sekunden-Challenge", "Reto de 30 segundos", "Výzva na 30 sekund"],
  ["Start Score Rush", "Punktejagd starten", "Iniciar carrera de puntos", "Spustit honbu za body"],
  ["Recent Runs", "Letzte Runden", "Rondas recientes", "Nedávná kola"],
  ["Your latest attempts", "Deine letzten Versuche", "Tus últimos intentos", "Vaše poslední pokusy"],
  ["No runs yet", "Noch keine Runden", "Aún no hay rondas", "Zatím žádná kola"],
  ["Leaderboard", "Rangliste", "Clasificación", "Žebříček"],
  ["Today's fastest minds", "Die Schnellsten von heute", "Las mentes más rápidas de hoy", "Dnešní nejrychlejší hráči"],
  ["You", "Du", "Tú", "Vy"],
  ["points", "Punkte", "puntos", "bodů"],
  ["Time's up", "Zeit abgelaufen", "Se acabó el tiempo", "Čas vypršel"],
  ["Top Score Rush Players", "Beste Punktejagd-Spieler", "Mejores jugadores", "Nejlepší hráči"],

  ["Deck Editor", "Deck-Editor", "Editor de mazos", "Editor balíčků"],
  ["Sign in to edit decks", "Melde dich an, um Decks zu bearbeiten", "Inicia sesión para editar mazos", "Přihlaste se pro úpravu balíčků"],
  ["Your decks are synced to your account.", "Deine Decks werden mit deinem Konto synchronisiert.", "Tus mazos se sincronizan con tu cuenta.", "Vaše balíčky se synchronizují s účtem."],
  ["Create custom decks by language pair and edit words in each deck.", "Erstelle Decks nach Sprachpaar und bearbeite ihre Wörter.", "Crea mazos por pareja de idiomas y edita sus palabras.", "Vytvářejte balíčky podle jazykové dvojice a upravujte jejich slova."],
  ["Generate with AI", "Mit KI erstellen", "Generar con IA", "Vytvořit pomocí AI"],
  ["Describe a topic and let AI build the deck.", "Beschreibe ein Thema und lass die KI das Deck erstellen.", "Describe un tema y deja que la IA cree el mazo.", "Popište téma a nechte AI vytvořit balíček."],
  ["Decks", "Decks", "Mazos", "Balíčky"],
  ["New deck", "Neues Deck", "Nuevo mazo", "Nový balíček"],
  ["Create", "Erstellen", "Crear", "Vytvořit"],
  ["Cancel", "Abbrechen", "Cancelar", "Zrušit"],
  ["No decks yet — tap + to create one.", "Noch keine Decks – tippe auf +, um eines zu erstellen.", "Todavía no hay mazos; toca + para crear uno.", "Zatím žádné balíčky — klepnutím na + jeden vytvořte."],
  ["Choose a deck to start editing.", "Wähle ein Deck zum Bearbeiten.", "Elige un mazo para editarlo.", "Vyberte balíček, který chcete upravit."],
  ["Deck Name", "Deckname", "Nombre del mazo", "Název balíčku"],
  ["Native", "Muttersprache", "Nativo", "Rodný jazyk"],
  ["Foreign", "Fremdsprache", "Extranjero", "Cizí jazyk"],
  ["Action", "Aktion", "Acción", "Akce"],
  ["Actions", "Aktionen", "Acciones", "Akce"],
  ["Add Word", "Wort hinzufügen", "Añadir palabra", "Přidat slovo"],
  ["Delete", "Löschen", "Eliminar", "Smazat"],
  ["Edit", "Bearbeiten", "Editar", "Upravit"],
  ["Save", "Speichern", "Guardar", "Uložit"],
  ["Share", "Teilen", "Compartir", "Sdílet"],
  ["No words added yet. Add your first word above!", "Noch keine Wörter. Füge oben dein erstes hinzu!", "Todavía no hay palabras. Añade la primera arriba.", "Zatím nejsou přidána žádná slova. Přidejte první výše."],

  ["Friends", "Freunde", "Amigos", "Přátelé"],
  ["My friends", "Meine Freunde", "Mis amigos", "Moji přátelé"],
  ["Add friend", "Freund hinzufügen", "Añadir amigo", "Přidat přítele"],
  ["Add as friend", "Als Freund hinzufügen", "Añadir como amigo", "Přidat jako přítele"],
  ["Already added", "Bereits hinzugefügt", "Ya está añadido", "Již přidán"],
  ["Search by tag (example: kuba19, kubafox44)", "Nach Tag suchen (z. B. kuba19, kubafox44)", "Buscar por etiqueta (ejemplo: kuba19, kubafox44)", "Hledat podle značky (např. kuba19, kubafox44)"],
  ["Clear", "Leeren", "Borrar", "Vymazat"],
  ["Open profile", "Profil öffnen", "Abrir perfil", "Otevřít profil"],
  ["Friend profile", "Freundesprofil", "Perfil de amigo", "Profil přítele"],
  ["Profile not found", "Profil nicht gefunden", "No se encontró el perfil", "Profil nebyl nalezen"],
  ["Back to Friends", "Zurück zu Freunde", "Volver a Amigos", "Zpět na Přátele"],
  ["Profile code", "Profilcode", "Código de perfil", "Kód profilu"],
  ["Status", "Status", "Estado", "Stav"],
  ["League", "Liga", "Liga", "Liga"],
  ["Matches", "Spiele", "Partidas", "Zápasy"],
  ["Display name", "Anzeigename", "Nombre visible", "Zobrazované jméno"],
  ["Background", "Hintergrund", "Fondo", "Pozadí"],
  ["Close", "Schließen", "Cerrar", "Zavřít"],
  ["Choose", "Auswählen", "Elegir", "Vybrat"],

  ["Level", "Level", "Nivel", "Úroveň"],
  ["words mastered", "gemeisterte Wörter", "palabras dominadas", "zvládnutých slov"],
  ["Take the level", "Leveltest", "Hacer la prueba de nivel", "Spustit test úrovně"],
  ["Building your test...", "Test wird erstellt…", "Preparando la prueba…", "Připravuji test…"],
  ["Previous", "Zurück", "Anterior", "Předchozí"],
  ["Next", "Weiter", "Siguiente", "Další"],
  ["Answer all", "Beantworte alle", "Responde las", "Odpovězte na všech"],
  ["questions to finish.", "Fragen, um abzuschließen.", "preguntas para terminar.", "otázek pro dokončení."],
  ["Retake the test", "Test wiederholen", "Repetir la prueba", "Opakovat test"],

  ["You're offline", "Du bist offline", "Estás sin conexión", "Jste offline"],
  ["This page needs a connection. Decks you downloaded for offline use are still there — open My Decks and keep practising.", "Diese Seite braucht eine Verbindung. Heruntergeladene Decks sind weiterhin verfügbar – öffne Meine Decks und übe weiter.", "Esta página necesita conexión. Los mazos descargados siguen disponibles; abre Mis mazos y continúa practicando.", "Tato stránka potřebuje připojení. Stažené balíčky jsou stále dostupné — otevřete Moje balíčky a procvičujte dál."],
  ["Go to My Decks", "Zu Meine Decks", "Ir a Mis mazos", "Přejít na Moje balíčky"],
  ["Try again", "Erneut versuchen", "Intentar de nuevo", "Zkusit znovu"],
  ["Waiting for a connection…", "Warten auf Verbindung…", "Esperando conexión…", "Čekám na připojení…"],
  ["A new version of KatchUp is ready.", "Eine neue KatchUp-Version ist bereit.", "Hay una nueva versión de KatchUp disponible.", "Je připravena nová verze KatchUp."],
  ["Later", "Später", "Más tarde", "Později"],
  ["Reload", "Neu laden", "Recargar", "Načíst znovu"],
  ["Thank you for supporting KatchUp!", "Danke für deine Unterstützung!", "¡Gracias por apoyar KatchUp!", "Děkujeme za podporu KatchUp!"],
  ["Your donation was completed securely through Stripe.", "Deine Spende wurde sicher über Stripe abgeschlossen.", "Tu donación se completó de forma segura mediante Stripe.", "Váš příspěvek byl bezpečně dokončen přes Stripe."],
  ["Back to KatchUp", "Zurück zu KatchUp", "Volver a KatchUp", "Zpět na KatchUp"],

  ["Learning Tips & Language Notes", "Lerntipps & Sprachwissen", "Consejos y notas de idiomas", "Tipy k učení a jazykové poznámky"],
  ["Read", "Lesen", "Leer", "Číst"],
  ["Back to blog", "Zurück zum Blog", "Volver al blog", "Zpět na blog"],
  ["More on", "Mehr zu", "Más sobre", "Více o"],
  ["Blog", "Blog", "Blog", "Blog"],
  ["Short, practical articles about learning English, German, and Spanish — habits, grammar shortcuts, and common mistakes worth fixing early.", "Kurze, praktische Artikel über Englisch, Deutsch und Spanisch – Gewohnheiten, Grammatik-Abkürzungen und typische Fehler.", "Artículos breves y prácticos sobre inglés, alemán y español: hábitos, atajos gramaticales y errores que conviene corregir pronto.", "Krátké praktické články o angličtině, němčině a španělštině — návyky, gramatické zkratky a časté chyby."],

  ["Back", "Zurück", "Volver", "Zpět"],
  ["You're offline. Decks can only be created and edited with a connection — downloaded decks are still practisable from My Decks.", "Du bist offline. Decks können nur mit Verbindung erstellt und bearbeitet werden; heruntergeladene Decks kannst du unter Meine Decks weiterüben.", "Estás sin conexión. Solo puedes crear y editar mazos con conexión; los mazos descargados siguen disponibles en Mis mazos.", "Jste offline. Balíčky lze vytvářet a upravovat jen s připojením; stažené balíčky můžete dál procvičovat v Moje balíčky."],
  ["Sign in to generate decks with AI.", "Melde dich an, um Decks mit KI zu erstellen.", "Inicia sesión para generar mazos con IA.", "Přihlaste se pro vytváření balíčků pomocí AI."],
  ["Words", "Wörter", "Palabras", "Slova"],
  ["words", "Wörter", "palabras", "slov"],
  ["Language", "Sprache", "Idioma", "Jazyk"],
  ["Add", "Hinzufügen", "Añadir", "Přidat"],
  ["Primary Words", "Hauptwörter", "Palabras principales", "Hlavní slova"],
  ["Native Word", "Wort in der Muttersprache", "Palabra nativa", "Slovo v rodném jazyce"],
  ["Foreign Translation", "Fremdsprachige Übersetzung", "Traducción", "Překlad"],
  ["Foreign Language", "Fremdsprache", "Idioma extranjero", "Cizí jazyk"],
  ["Or Upload", "Oder hochladen", "O subir", "Nebo nahrát"],
  ["File", "Datei", "Archivo", "Soubor"],
  ["Upload", "Hochladen", "Subir", "Nahrát"],
  ["This will permanently delete", "Dadurch wird dauerhaft gelöscht:", "Esto eliminará permanentemente", "Tímto trvale smažete"],
  ["and all its words. Type its name to confirm.", "und alle enthaltenen Wörter. Gib den Namen zur Bestätigung ein.", "y todas sus palabras. Escribe su nombre para confirmar.", "a všechna jeho slova. Potvrďte zadáním názvu."],

  ["Set up your languages", "Sprachen einrichten", "Configura tus idiomas", "Nastavte své jazyky"],
  ["Pick the pair, then a short test places you. Do well and you start higher — there is no way to skip it.", "Wähle dein Sprachenpaar; ein kurzer Test bestimmt dann dein Level. Mit guten Antworten startest du höher – überspringen lässt er sich nicht.", "Elige la pareja de idiomas y una prueba corta determinará tu nivel. Si lo haces bien, empezarás más arriba; no se puede omitir.", "Vyberte jazykovou dvojici a krátký test určí vaši úroveň. Když uspějete, začnete výš — test nelze přeskočit."],
  ["I want to learn", "Ich möchte lernen", "Quiero aprender", "Chci se učit"],
  ["Already have an account? Sign in", "Schon ein Konto? Anmelden", "¿Ya tienes cuenta? Inicia sesión", "Už máte účet? Přihlaste se"],
  ["Change languages", "Sprachen ändern", "Cambiar idiomas", "Změnit jazyky"],
  ["Languages", "Sprachen", "Idiomas", "Jazyky"],
  ["Pick the language you speak and the one you're learning. Each one keeps its own level.", "Wähle deine Sprache und die Sprache, die du lernst. Jede hat ihren eigenen Fortschritt.", "Elige el idioma que hablas y el que estás aprendiendo. Cada uno conserva su propio nivel.", "Vyberte jazyk, kterým mluvíte, a ten, který se učíte. Každý má vlastní úroveň."],

  ["Go head-to-head with another player in real time. Pick the right translation faster than your rival - first to 10 correct answers wins. No one online? Duel the bot instead.", "Tritt in Echtzeit gegen andere an. Wähle schneller die richtige Übersetzung; wer zuerst 10 richtige Antworten hat, gewinnt. Niemand online? Spiele gegen den Bot.", "Compite en tiempo real contra otra persona. Elige la traducción correcta más rápido; gana quien llegue primero a 10 aciertos. ¿No hay nadie? Juega contra el bot.", "Soutěžte v reálném čase proti hráči. Vyberte překlad rychleji; vyhrává první s 10 správnými odpověďmi. Nikdo online? Hrajte s botem."],
  ["You against the clock. Answer as many translations as you can in 30 seconds, then push your score onto the leaderboard.", "Du gegen die Uhr: Löse in 30 Sekunden so viele Übersetzungen wie möglich und bring deine Punkte in die Rangliste.", "Tú contra el reloj: responde tantas traducciones como puedas en 30 segundos y sube tu puntuación a la clasificación.", "Vy proti času: za 30 sekund odpovězte na co nejvíce překladů a dostaňte skóre do žebříčku."],
  ["A calm, no-timer deck for real study. Tap to flip between your language and the translation, swipe right when you know it or left to keep practicing.", "Ein ruhiges Deck ohne Zeitdruck. Tippe zum Umdrehen; wische nach rechts, wenn du das Wort kennst, oder nach links zum Weiterüben.", "Un mazo tranquilo y sin temporizador. Toca para girar; desliza a la derecha si conoces la palabra o a la izquierda para seguir practicando.", "Klidný balíček bez časovače. Klepnutím otočte kartu; přejeďte doprava, když slovo znáte, nebo doleva pro další procvičování."],
  ["Pick the right translation out of three options before time runs out. Simple to learn, tough to master, and built for quick daily reps.", "Wähle die richtige von drei Übersetzungen, bevor die Zeit abläuft. Leicht zu lernen, schwer zu meistern und ideal für tägliche Kurzrunden.", "Elige la traducción correcta entre tres opciones antes de que acabe el tiempo. Fácil de aprender, difícil de dominar y perfecto para practicar cada día.", "Vyberte správný překlad ze tří možností před vypršením času. Snadné na pochopení, těžké na zvládnutí a ideální pro každodenní procvičování."],

  ["You start at", "Du startest auf", "Empiezas en", "Začínáte na"],
  ["Passed — welcome to level", "Bestanden – willkommen auf Level", "Superado: bienvenido al nivel", "Splněno — vítejte na úrovni"],
  ["You jumped from level", "Du bist aufgestiegen von Level", "Has subido del nivel", "Postoupili jste z úrovně"],
  ["Not quite —", "Noch nicht –", "Casi, pero no:", "Ještě ne —"],
  ["% is needed to move up.", "% werden zum Aufstieg benötigt.", "% para subir de nivel.", "% je potřeba pro postup."],
  ["You're still level", "Du bleibst auf Level", "Sigues en el nivel", "Zůstáváte na úrovni"],
  [". Practise a little and try again.", ". Übe ein wenig und versuche es erneut.", ". Practica un poco e inténtalo de nuevo.", ". Trochu procvičujte a zkuste to znovu."],
  ["Keep level", "Level behalten", "Mantener nivel", "Ponechat úroveň"],
  ["Sign in and this result goes on your account. Without one there is nowhere to save it, and nothing to play.", "Melde dich an, damit das Ergebnis in deinem Konto gespeichert wird. Ohne Konto kann es nicht gespeichert werden.", "Inicia sesión para guardar este resultado en tu cuenta. Sin cuenta no se puede guardar ni continuar jugando.", "Přihlaste se a výsledek se uloží k účtu. Bez účtu ho není kam uložit ani pokračovat ve hře."],
  ["These get harder as they go, and they are not in order. Answer what you know and guess the rest — you start wherever the answers say, which may well be higher than you expect. Leave now and you start this over.", "Die Fragen werden schwieriger und sind nicht sortiert. Beantworte, was du weißt, und rate den Rest – deine Antworten bestimmen dein Startlevel. Wenn du jetzt gehst, beginnst du von vorn.", "Las preguntas se vuelven más difíciles y no están ordenadas. Responde lo que sepas y adivina el resto; tus respuestas decidirán tu nivel inicial. Si sales, tendrás que empezar de nuevo.", "Otázky se postupně ztěžují a nejsou seřazené. Odpovězte, co víte, zbytek tipněte — odpovědi určí vaši úroveň. Když odejdete, začnete znovu."],

  ["The QR code or profile code did not match a saved profile.", "Der QR- oder Profilcode gehört zu keinem gespeicherten Profil.", "El código QR o de perfil no coincide con ningún perfil guardado.", "QR kód ani kód profilu neodpovídá uloženému profilu."],
  ["QR code", "QR-Code", "Código QR", "QR kód"],
  ["Generating QR code...", "QR-Code wird erstellt…", "Generando código QR…", "Generuji QR kód…"],
  ["Scan the QR code or open the profile link to jump here.", "Scanne den QR-Code oder öffne den Profillink.", "Escanea el código QR o abre el enlace del perfil.", "Naskenujte QR kód nebo otevřete odkaz na profil."],
  ["Edit look & code", "Aussehen & Code ändern", "Editar aspecto y código", "Upravit vzhled a kód"],
  ["Practice XP", "Übungs-XP", "XP de práctica", "XP za procvičování"],
  ["Add me", "Füge mich hinzu", "Añádeme", "Přidej si mě"],
  ["Unique code", "Eindeutiger Code", "Código único", "Jedinečný kód"],
  ["Generating QR...", "QR-Code wird erstellt…", "Generando QR…", "Generuji QR…"],
  ["Joined", "Beigetreten", "Se unió", "Přidán"],
  ["Friend Quest", "Freundesmission", "Misión de amigos", "Výzva pro přátele"],
  ["Who's your buddy this week?", "Wer ist diese Woche dein Partner?", "¿Quién será tu compañero esta semana?", "Kdo je tento týden váš parťák?"],
  ["Add a friend below first, then pick them here to start your weekly duo.", "Füge unten zuerst einen Freund hinzu und wähle ihn dann hier für euer Wochenteam.", "Añade primero un amigo abajo y elígelo aquí para formar el dúo semanal.", "Nejprve dole přidejte přítele a pak ho zde vyberte do týdenní dvojice."],
  ["Buddy this week", "Partner diese Woche", "Compañero de esta semana", "Parťák na tento týden"],
  ["Change buddy", "Partner wechseln", "Cambiar compañero", "Změnit parťáka"],
  ["Make it yours", "Mach es zu deinem", "Hazlo tuyo", "Upravte si podle sebe"],
  ["This is the name your friends see. It defaults to your first name — change it to whatever you like.", "Diesen Namen sehen deine Freunde. Standardmäßig ist es dein Vorname; du kannst ihn frei ändern.", "Este es el nombre que ven tus amigos. Al principio es tu nombre, pero puedes cambiarlo como quieras.", "Toto jméno uvidí přátelé. Výchozí je vaše křestní jméno, ale můžete ho libovolně změnit."],
  ["Cute icon", "Niedliches Symbol", "Icono adorable", "Roztomilá ikona"],
  ["Generate cute icon", "Niedliches Symbol erstellen", "Generar icono adorable", "Vytvořit roztomilou ikonu"],
  ["Save code", "Code speichern", "Guardar código", "Uložit kód"],

  ["First to", "Als Erstes", "El primero en llegar a", "První s"],
  ["correct answers wins", "richtigen Antworten gewinnt", "respuestas correctas gana", "správnými odpověďmi vyhrává"],
  ["Question", "Frage", "Pregunta", "Otázka"],
  ["correct", "richtig", "correctas", "správně"],
  ["Confirming the result...", "Ergebnis wird bestätigt…", "Confirmando el resultado…", "Potvrzuji výsledek…"],
  ["It was closed or is no longer available. Start a fresh one from the lobby.", "Es wurde geschlossen oder ist nicht mehr verfügbar. Starte in der Lobby ein neues Duell.", "Se cerró o ya no está disponible. Inicia uno nuevo desde la sala.", "Byl uzavřen nebo už není dostupný. Spusťte nový z lobby."],
  ["You're out of prompts", "Du hast keine Aufgaben mehr", "Ya no te quedan preguntas", "Došly vám otázky"],
  ["to finish...", "bis zum Ende…", "para que termine…", "na dokončení…"],
  ["Loading the duel...", "Duell wird geladen…", "Cargando el duelo…", "Načítám souboj…"],
  ["Total points:", "Gesamtpunkte:", "Puntos totales:", "Celkem bodů:"],
  ["That was your free bot duel!", "Das war dein kostenloses Bot-Duell!", "¡Ese era tu duelo gratuito contra el bot!", "To byl váš bezplatný souboj s botem!"],
  ["Sign in to save your progress and keep duelling.", "Melde dich an, um deinen Fortschritt zu speichern und weiterzuspielen.", "Inicia sesión para guardar tu progreso y seguir jugando.", "Přihlaste se pro uložení pokroku a další souboje."],
  ["Sign in to keep playing", "Zum Weiterspielen anmelden", "Inicia sesión para seguir jugando", "Přihlaste se a pokračujte ve hře"],
  ["Language pair and the level picked from your progress", "Sprachenpaar und Level aus deinem Fortschritt", "Pareja de idiomas y nivel según tu progreso", "Jazyková dvojice a úroveň podle vašeho pokroku"],
  ["Your level of language & vocabulary", "Dein Sprach- und Wortschatzlevel", "Tu nivel de idioma y vocabulario", "Vaše jazyková úroveň a slovní zásoba"],
  ["Match with a live opponent and race to 10 correct answers.", "Finde einen Live-Gegner und erreiche zuerst 10 richtige Antworten.", "Encuentra un rival y llega primero a 10 respuestas correctas.", "Najděte živého soupeře a získejte jako první 10 správných odpovědí."],
  ["Decline duel", "Duell ablehnen", "Rechazar duelo", "Odmítnout souboj"],
  ["Expires in", "Läuft ab in", "Caduca en", "Vyprší za"],
  ["Cancelling in", "Abbruch in", "Se cancelará en", "Zrušení za"],

  ["Not quite, keep trying", "Noch nicht, versuch es weiter", "Casi, sigue intentándolo", "Ještě ne, zkoušejte dál"],
  ["A calm, self-paced flashcard deck. Tap a card to flip between your language and the translation, then swipe right if you knew it or left to keep practicing it.", "Ein ruhiges Lernkartendeck ohne Zeitdruck. Tippe zum Umdrehen; wische nach rechts, wenn du das Wort kennst, oder nach links zum Weiterüben.", "Un mazo de tarjetas tranquilo y a tu ritmo. Toca para girar; desliza a la derecha si conoces la palabra o a la izquierda para seguir practicando.", "Klidný balíček kartiček vlastním tempem. Klepnutím otočte kartu; přejeďte doprava, když slovo znáte, nebo doleva pro další procvičování."],
  ["Swipe the card, or use the buttons below", "Wische die Karte oder nutze die Tasten unten", "Desliza la tarjeta o usa los botones", "Přejeďte kartou nebo použijte tlačítka níže"],
  ["I'm still learning this one", "Das lerne ich noch", "Todavía estoy aprendiendo esta", "Tohle se stále učím"],
  ["I know this one", "Das weiß ich", "Esta la sé", "Tohle znám"],
  ["This pack is now legendary", "Dieses Paket ist jetzt legendär", "Este paquete ya es legendario", "Tento balíček je nyní legendární"],
  ["Scoring the round...", "Runde wird ausgewertet…", "Calculando la ronda…", "Vyhodnocuji kolo…"],
  ["% needed for legendary", "% für legendär benötigt", "% necesario para legendario", "% potřeba pro legendární stav"],
  ["Deck complete", "Deck abgeschlossen", "Mazo completado", "Balíček dokončen"],
  ["% known", "% gewusst", "% conocidas", "% známých"],
  ["Run the round again to take the crown.", "Spiele die Runde erneut, um die Krone zu holen.", "Repite la ronda para conseguir la corona.", "Zopakujte kolo a získejte korunu."],
  ["known", "gewusst", "conocidas", "znám"],
  ["still learning", "noch am Lernen", "aún aprendiendo", "stále se učím"],

  ["Loading recent runs", "Letzte Runden werden geladen", "Cargando rondas recientes", "Načítám nedávná kola"],
  ["Answer fast, build your score, and take your place on the leaderboard. Every correct answer counts.", "Antworte schnell, sammle Punkte und sichere dir einen Ranglistenplatz. Jede richtige Antwort zählt.", "Responde rápido, suma puntos y consigue tu puesto en la clasificación. Cada respuesta correcta cuenta.", "Odpovídejte rychle, sbírejte body a získejte místo v žebříčku. Každá správná odpověď se počítá."],
  ["Start a 30 second Score Rush", "30-Sekunden-Punktejagd starten", "Iniciar una carrera de puntos de 30 segundos", "Spustit 30sekundovou honbu za body"],
  ["30 seconds on the clock. Answer as fast and accurately as you can.", "30 Sekunden auf der Uhr. Antworte so schnell und genau wie möglich.", "Tienes 30 segundos. Responde tan rápido y bien como puedas.", "Na hodinách je 30 sekund. Odpovídejte co nejrychleji a nejpřesněji."],
  ["Your results will appear here after your first rush.", "Nach deiner ersten Runde erscheinen hier die Ergebnisse.", "Tus resultados aparecerán aquí después de la primera ronda.", "Po prvním kole se zde zobrazí výsledky."],
  ["Top 4 + You", "Top 4 + Du", "Los 4 mejores + tú", "Nejlepší 4 + vy"],
  ["The board is wide open", "Die Rangliste wartet auf dich", "La clasificación está libre", "Žebříček je otevřený"],
  ["Finish a run and set the score to beat.", "Beende eine Runde und setze die Bestmarke.", "Completa una ronda y marca la puntuación a superar.", "Dokončete kolo a stanovte skóre, které ostatní překonají."],
  ["First place", "Erster Platz", "Primer puesto", "První místo"],

  ["Match each word with its translation before the mistakes pile up. Reach 70% accuracy to complete the lesson.", "Ordne jedes Wort seiner Übersetzung zu, bevor sich Fehler häufen. Mit 70 % Genauigkeit schließt du die Lektion ab.", "Empareja cada palabra con su traducción antes de acumular errores. Alcanza un 70 % de precisión para completar la lección.", "Spojte každé slovo s překladem dříve, než se nahromadí chyby. Pro dokončení lekce dosáhněte 70% přesnosti."],
  ["Synonym Match", "Wortpaare", "Emparejar palabras", "Párování slov"],
  ["Matched", "Zugeordnet", "Emparejadas", "Spárováno"],
  ["Mistakes:", "Fehler:", "Errores:", "Chyby:"],
  ["Tap a word, then tap its match", "Tippe auf ein Wort und dann auf sein Gegenstück", "Toca una palabra y luego su pareja", "Klepněte na slovo a potom na jeho protějšek"],
  ["mistake", "Fehler", "error", "chyba"],
  ["Next level →", "Nächstes Level →", "Siguiente nivel →", "Další úroveň →"],
  ["Pick the correct word from three options. Reach 70% to complete the lesson automatically.", "Wähle das richtige Wort aus drei Optionen. Mit 70 % wird die Lektion automatisch abgeschlossen.", "Elige la palabra correcta entre tres opciones. Alcanza un 70 % para completar la lección automáticamente.", "Vyberte správné slovo ze tří možností. Při 70 % se lekce automaticky dokončí."],
  ["You've used your free round", "Du hast deine kostenlose Runde genutzt", "Ya has usado tu ronda gratuita", "Využili jste bezplatné kolo"],
  ["Translation Sprint", "Übersetzungs-Sprint", "Sprint de traducción", "Překladatelský sprint"],
  ["What matches this word?", "Was passt zu diesem Wort?", "¿Qué corresponde a esta palabra?", "Co odpovídá tomuto slovu?"],
  ["You picked a higher starting point than that round backed up, so we've eased it down. You'll start on words that fit and climb from there.", "Dein gewählter Startpunkt war höher, als die Runde bestätigt hat. Wir haben ihn angepasst; du beginnst mit passenden Wörtern und arbeitest dich hoch.", "Elegiste un punto de partida más alto de lo que confirmó la ronda, así que lo hemos ajustado. Empezarás con palabras adecuadas y subirás desde ahí.", "Zvolili jste vyšší start, než kolo potvrdilo, proto jsme ho upravili. Začnete se slovy, která vám sedí, a budete postupovat výš."],
  ["Free round done — sign up to keep going and save your progress.", "Kostenlose Runde beendet – registriere dich, um weiterzuspielen und deinen Fortschritt zu speichern.", "Ronda gratuita terminada; regístrate para continuar y guardar tu progreso.", "Bezplatné kolo skončilo — zaregistrujte se pro pokračování a uložení pokroku."],

  ["You’re offline", "Du bist offline", "Estás sin conexión", "Jste offline"],
  ["Anything you practise offline is saved on this device and syncs the moment you’re back online.", "Alles, was du offline übst, wird auf diesem Gerät gespeichert und synchronisiert, sobald du wieder online bist.", "Todo lo que practiques sin conexión se guardará en este dispositivo y se sincronizará cuando vuelvas a conectarte.", "Vše, co procvičujete offline, se uloží v tomto zařízení a synchronizuje se po návratu online."],
  ["Legendary", "Legendär", "Legendario", "Legendární"],
  ["Open pack", "Paket öffnen", "Abrir paquete", "Otevřít balíček"],
  ["Just completed", "Gerade abgeschlossen", "Recién completado", "Právě dokončeno"],
  ["Blog — KatchUp", "Blog — KatchUp", "Blog — KatchUp", "Blog — KatchUp"],
  ["Tips, guides, and habits for learning English, German, and Spanish.", "Tipps, Anleitungen und Gewohnheiten zum Lernen von Englisch, Deutsch und Spanisch.", "Consejos, guías y hábitos para aprender inglés, alemán y español.", "Tipy, návody a návyky pro studium angličtiny, němčiny a španělštiny."],
  ["Offline — KatchUp", "Offline — KatchUp", "Sin conexión — KatchUp", "Offline — KatchUp"],
  ["You're offline. Downloaded decks are still ready to practise.", "Du bist offline. Heruntergeladene Decks sind weiter zum Üben verfügbar.", "Estás sin conexión. Los mazos descargados siguen disponibles para practicar.", "Jste offline. Stažené balíčky jsou stále připravené k procvičování."],
  ["KatchUp — learn words that stick", "KatchUp — Wörter lernen, die bleiben", "KatchUp — aprende palabras que recordarás", "KatchUp — učte se slova, která si zapamatujete"],
  ["Practice vocabulary in short rounds, race your friends, and keep your streak — online or off.", "Übe Wortschatz in kurzen Runden, tritt gegen Freunde an und halte deine Serie – online wie offline.", "Practica vocabulario en rondas cortas, compite con tus amigos y mantén tu racha, con o sin conexión.", "Procvičujte slovní zásobu v krátkých kolech, soutěžte s přáteli a udržujte sérii — online i offline."],

  ["You’re offline. Decks can only be created and edited with a connection — downloaded decks are still practisable from My Decks.", "Du bist offline. Decks können nur mit Verbindung erstellt und bearbeitet werden; heruntergeladene Decks kannst du unter Meine Decks weiterüben.", "Estás sin conexión. Solo puedes crear y editar mazos con conexión; los mazos descargados siguen disponibles en Mis mazos.", "Jste offline. Balíčky lze vytvářet a upravovat jen s připojením; stažené balíčky můžete dál procvičovat v Moje balíčky."],
  ["✨ Generate with AI", "✨ Mit KI erstellen", "✨ Generar con IA", "✨ Vytvořit pomocí AI"],
  ["belongs to", "gehört", "pertenece a", "patří uživateli"],
  [". It leaves your list; their deck stays as it is.", ". Es verschwindet aus deiner Liste; das ursprüngliche Deck bleibt unverändert.", ". Desaparecerá de tu lista, pero el mazo original no cambiará.", ". Z vašeho seznamu zmizí, ale původní balíček zůstane beze změny."],
  ["Word Database (", "Wortdatenbank (", "Base de palabras (", "Databáze slov ("],
  ["word", "Wort", "palabra", "slovo"],
  ["of", "von", "de", "z"],
  ["in", "in", "en", "v"],
  ["more", "weitere", "más", "dalších"],
  ["to reach", "bis", "para llegar a", "do dosažení"],
  ["— the top of the ladder. Keep the streak going!", "– ganz oben. Halte deine Serie am Laufen!", "— la cima. ¡Mantén la racha!", "— vrchol žebříčku. Pokračujte v sérii!"],
  ["more mastered", "weitere gemeistert", "más dominadas", "dalších zvládnutých"],
  ["gets you to level", "bringen dich auf Level", "te llevan al nivel", "vás posune na úroveň"],
  ["— or earn it now by passing the level", "– oder erreiche es jetzt mit dem Leveltest", "— o consíguelo ahora superando la prueba de nivel", "— nebo ji získejte splněním testu úrovně"],
  ["test with", "mit", "con", "s"],
  ["test", "Test", "prueba", "test"],
  ["· answer in", "· antworte auf", "· responde en", "· odpovězte v"],
  ["— level", "– Level", "— nivel", "— úroveň"],
  ["to level", "auf Level", "al nivel", "na úroveň"],
  ["words).", "Wörter).", "palabras).", "slov)."],
  ["normally takes", "benötigt normalerweise", "normalmente requiere", "obvykle vyžaduje"],
  ["mastered words — score", "gemeisterte Wörter – erreiche", "palabras dominadas; consigue", "zvládnutých slov — získejte"],
  ["% to skip straight to it.", "%, um direkt dorthin zu springen.", "% para saltar directamente a ese nivel.", "% pro přímý postup na tuto úroveň."],

  ["my little home", "mein kleines Zuhause", "mi pequeño hogar", "můj malý domov"],
  ["total", "insgesamt", "en total", "celkem"],
  ["tag:", "Tag:", "etiqueta:", "značka:"],
  ["No friends yet — search a tag above to add your first one.", "Noch keine Freunde – suche oben nach einem Tag, um den ersten hinzuzufügen.", "Todavía no hay amigos; busca una etiqueta arriba para añadir el primero.", "Zatím žádní přátelé — vyhledejte značku výše a přidejte prvního."],
  ["Team up with one friend, tick off this week's tasks, and you both cozy up", "Schließ dich mit einem Freund zusammen, erledigt die Wochenaufgaben und sammelt gemeinsam", "Forma equipo con un amigo, completad las tareas de la semana y conseguid juntos", "Spojte se s přítelem, plňte týdenní úkoly a společně získávejte"],
  ["Asymmetric custom/recent vocabulary", "Unterschiedlicher eigener/aktueller Wortschatz", "Vocabulario personalizado o reciente distinto", "Rozdílná vlastní nebo nedávná slovní zásoba"],
  ["Type the correct word before the timer runs out. Reach 70% to complete the lesson.", "Tippe das richtige Wort, bevor die Zeit abläuft. Mit 70 % schließt du die Lektion ab.", "Escribe la palabra correcta antes de que acabe el tiempo. Alcanza un 70 % para completar la lección.", "Napište správné slovo před vypršením času. Pro dokončení lekce dosáhněte 70 %."],
  ["s left", "s übrig", "s restantes", "s zbývá"],
  ["✓ I already know this", "✓ Das weiß ich schon", "✓ Ya conozco esta palabra", "✓ Tohle už znám"],
  ["Show", "Anzeigen", "Mostrar", "Zobrazit"],
  ["One more go", "Noch ein Versuch", "Un intento más", "Ještě jednou"],
  ["Restart", "Neu starten", "Reiniciar", "Začít znovu"],
  ["Paused", "Pausiert", "En pausa", "Pozastaveno"],
  ["Resume", "Fortsetzen", "Reanudar", "Pokračovat"],
  ["Exit", "Beenden", "Salir", "Ukončit"],
  ["Pause", "Pause", "Pausa", "Pauza"],
  ["🏁 Finish round", "🏁 Runde beenden", "🏁 Terminar ronda", "🏁 Dokončit kolo"],
  ["Review the", "Wiederhole die", "Repasa las", "Zopakujte"],
  ["you're learning", "die du noch lernst", "que estás aprendiendo", "která se učíte"],
  ["correct answers", "richtige Antworten", "respuestas correctas", "správných odpovědí"],
  ["/5 levels", "/5 Level", "/5 niveles", "/5 úrovní"],

  ["Opponent", "Gegner", "Rival", "Soupeř"],
  ["DECK: TRAVEL", "DECK: REISEN", "MAZO: VIAJES", "BALÍČEK: CESTOVÁNÍ"],
  ["DECK: FOOD", "DECK: ESSEN", "MAZO: COMIDA", "BALÍČEK: JÍDLO"],
  ["DECK: LIFE", "DECK: ALLTAG", "MAZO: VIDA", "BALÍČEK: ŽIVOT"],
  ["vocabulary", "Wortschatz", "vocabulario", "slovní zásoba"],
  ["🔥 5 DAY STREAK", "🔥 5-TAGE-SERIE", "🔥 RACHA DE 5 DÍAS", "🔥 SÉRIE 5 DNŮ"],
  ["Compete with Friends", "Mit Freunden messen", "Compite con amigos", "Soutěžte s přáteli"],
  ["Jump into fast language battles, track wins, and keep the rivalry alive with live score pressure.", "Stürze dich in schnelle Sprachduelle, verfolge deine Siege und halte die Rivalität mit Live-Punkten am Laufen.", "Entra en rápidos duelos de idiomas, registra tus victorias y mantén viva la rivalidad con puntuaciones en directo.", "Vrhněte se do rychlých jazykových soubojů, sledujte výhry a udržujte rivalitu díky živému skóre."],
  ["Add Your Own Words", "Eigene Wörter hinzufügen", "Añade tus propias palabras", "Přidejte vlastní slova"],
  ["Build personal decks from school, work, or travel vocabulary and train exactly what matters to you.", "Erstelle persönliche Decks mit Vokabeln aus Schule, Arbeit oder Reisen und übe genau das, was für dich zählt.", "Crea mazos personales con vocabulario de estudios, trabajo o viajes y practica justo lo que te importa.", "Vytvářejte vlastní balíčky ze slovní zásoby ze školy, práce nebo cest a procvičujte přesně to, co potřebujete."],
  ["See Real Progress", "Echte Fortschritte sehen", "Observa tu progreso real", "Sledujte skutečný pokrok"],
  ["Follow streaks, speed, and leaderboard rank so your improvement feels measurable every day.", "Verfolge Serien, Tempo und Ranglistenplatz, damit deine Fortschritte jeden Tag messbar werden.", "Sigue tus rachas, velocidad y posición para que tu mejora sea visible cada día.", "Sledujte série, rychlost a pozici v žebříčku, aby byl váš pokrok každý den měřitelný."],
  ["Language Learning Arena", "Arena zum Sprachenlernen", "Arena de aprendizaje de idiomas", "Aréna pro výuku jazyků"],
  ["Ready?", "Bereit?", "¿Listo?", "Připraveni?"],
  ["Train vocabulary in a modern way with", "Trainiere Wortschatz modern mit", "Entrena vocabulario de forma moderna con", "Procvičujte slovní zásobu moderně s"],
  [". Compete, customize, and improve with game-like energy.", ". Miss dich mit anderen, passe alles an und werde spielerisch besser.", ". Compite, personaliza y mejora con la energía de un juego.", ". Soutěžte, přizpůsobujte a zlepšujte se s energií hry."],
  ["Go to Decks", "Zu den Decks", "Ir a los mazos", "Přejít na balíčky"],
  ["Login / Register", "Anmelden / Registrieren", "Iniciar sesión / Registrarse", "Přihlásit / Registrovat"],
  ["Start Playing", "Spielen starten", "Empezar a jugar", "Začít hrát"],
  ["Your Next Session", "Deine nächste Runde", "Tu próxima sesión", "Vaše další lekce"],
  ["Turn 10 spare minutes into real vocabulary progress.", "Mach aus 10 freien Minuten echten Wortschatzfortschritt.", "Convierte 10 minutos libres en progreso real de vocabulario.", "Proměňte 10 volných minut ve skutečný pokrok ve slovní zásobě."],
  ["Open Games", "Spiele öffnen", "Abrir juegos", "Otevřít hry"],
];

const LANGUAGE_COLUMN: Record<Lang, number> = { en: 0, de: 1, es: 2, cs: 3 };
const phraseMap = new Map(PHRASES.map((row) => [row[0], row]));

export function translateLegacyUiText(value: string, language: Lang): string {
  if (language === "en") return value;

  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  const source = value.trim();
  const row = phraseMap.get(source);

  if (row) {
    return `${leading}${row[LANGUAGE_COLUMN[language]]}${trailing}`;
  }

  const run = source.match(/^Run (\d+)$/);
  if (run) {
    const labels: Record<Exclude<Lang, "en">, string> = {
      de: `Runde ${run[1]}`,
      es: `Ronda ${run[1]}`,
      cs: `Kolo ${run[1]}`,
    };
    return `${leading}${labels[language]}${trailing}`;
  }

  const score = source.match(/^Score: (\d+)$/);
  if (score) {
    const labels: Record<Exclude<Lang, "en">, string> = {
      de: `Punkte: ${score[1]}`,
      es: `Puntuación: ${score[1]}`,
      cs: `Skóre: ${score[1]}`,
    };
    return `${leading}${labels[language]}${trailing}`;
  }

  const destination = source.match(/^Go to (.+)$/);
  if (destination) {
    const translatedDestination = translateLegacyUiText(
      destination[1],
      language,
    );
    const labels: Record<Exclude<Lang, "en">, string> = {
      de: `Zu ${translatedDestination}`,
      es: `Ir a ${translatedDestination}`,
      cs: `Přejít na ${translatedDestination}`,
    };
    return `${leading}${labels[language]}${trailing}`;
  }

  return value;
}
